import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';

import Banner from '@/components/Banner';
import Card from '@/components/Card';

import { fetchCoffeeStores } from '@/lib/coffee-stores';

export default function Home(props) {
  const handleOnBannerClick = () => {
    console.log('handleOnBannerClick');
  };

  console.log('home', props);

  const items = props?.coffeeStores || [];

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner buttonText="View store nearby" handleOnClick={handleOnBannerClick} />
        <Image
          className={styles.heroImage}
          src="/static/hero-image.png"
          blurDataURL="/static/hero-image.png"
          width={700}
          height={400}
          alt="hero-image"
          placeholder="blur"
        />
        {items.length > 0 ? (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {items.map((item) => {
                return (
                  <Card
                    key={item.id}
                    name={item.name}
                    imgUrl={item.imgUrl}
                    href={`/coffee-store/${item.id}`}
                  />
                );
              })}
            </div>
          </>
        ) : null}
      </main>
    </>
  );
}

export async function getStaticProps() {
  const coffeeStores = await fetchCoffeeStores();
  return {
    props: {
      coffeeStores,
    },
  };
}
