import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';

import Banner from '@/components/Banner';
import Card from '@/components/Card';

export default function Home() {
  const handleOnBannerClick = () => {
    console.log('handleOnBannerClick');
  };
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner buttonText="View store nearby" handleOnClick={handleOnBannerClick} />
        <Image
          className={styles.heroImage}
          src="/static/hero-image.png"
          blurDataURL="/static/hero-image.png"
          width={700}
          height={400}
          alt="hero-image"
          placeholder="blur"
        />
        <Card name="DarkHouse" imgUrl="/static/hero-image.png" href="/coffee-store/darkhouse" />
      </main>
    </>
  );
}
